---
title: "BAMA_SummaryScript"
author: "Chelsea Crooks, Sergey Ananyev"
date: "2024-05-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#---- Clear Global Environment ----
rm(list = ls())

#---- Session prep ----

## Load packages ##
if(!require(tidyverse)) {
  install.packages("tidyverse", dependencies = T)
  library(tidyverse)
}
if(!require(ggplot2)){
  install.packages("ggplot2",dependencies = T)
  library(ggplot2)
}
if(!require(MESS)){
  install.packages("MESS",dependencies = T)
  library(MESS)
}
if(!require(gridExtra)){
  install.packages("gridExtra",dependencies = T)
  library(gridExtra)
}
if(!require(grid)){
  install.packages("grid",dependencies = T)
  library(grid)
}
if(!require(ggsignif)){
  install.packages("ggsignif",dependencies = T)
  library(ggsignif)
}
if(!require(data.table)){
  install.packages("data.table",dependencies = T)
  library(data.table)
}
if(!require(dplyr)){
  install.packages("dplyr",dependencies = T)
  library(dplyr)
}
if(!require(ggplate)){
  install.packages("ggplate",dependencies = T)
  library(ggplate)
}
if(!require(readxl)){
  install.packages("readxl",dependencies = T)
  library(readxl)
}
if(!require(pzfx)){
  install.packages("pzfx",dependencies = T)
  library(pzfx)
}
if(!require(readr)){
  install.packages("readr",dependencies = T)
  library(readr)
}
if(!require(naniar)){
  install.packages("naniar",dependencies = T)
  library(naniar)
}
if(!require(rlist)){
  install.packages("rlist",dependencies = T)
  library(rlist)
}
if(!require(drc)){
  install.packages("drc",dependencies = T)
  library(drc)
}
if(!require(stats)){
  install.packages("stats",dependencies = T)
  library(stats)
}
if(!require(tibble)){
  install.packages("tibble",dependencies = T)
  library(tibble)
}
if(!require(fuzzyjoin)){
  install.packages("fuzzyjoin",dependencies = T)
  library(fuzzyjoin)
}

### End of Session Prep ###


```

# Data Entry

```{r DataEntry}

# Step 1: Set workingDirectory as the location of your data folders

workingDirectory <- "Z:/Data/Adelaide Fuller/CMV/BAMA/"

# Step 2: Set folderMFI as the name of the folder that contains your MFI files

folderMFI <- "4_analyzed/CMV004_formal/RAW_MFIs/IgM/"

# Step 3: Set folderQC as the name of the folder that contains your QC files

folderQC <- "5_qc/CMV004_formal/IgM/"

# Step 4: Set folderOutput as the name of the folder that will contain the generated output

folderOutput <- "7_summary_files/IgM/"

# Step 5: Set projectName as your desired prefix that will be on every file generated by the script

projectName <- "IgM-SummaryScript_"

# Step 6: Enter the name of the primary QC script used to generate the MFI/CSV files

primaryQCscriptName <- "BAMA_PrimaryQC_Script_v1-SA"

### QC Criteria ###

# Step 6: Set the CV cutoff value

cvCutoff <- 25

# Step 7: Set the blank bead cutoff

blankBeadCutoff <- 500

# Step 8: Set the low bead count cutoff

lowBeadCountCutoff <- 100

# Step 9: Set the low MFI cutoff

lowMFI <- 100


```

# Remove Assays that don't pass QC

```{r RemoveAssaysThatDontPassQC}
# Step 1: Check to make sure all of the files are present

# import a list of all of the file names in the specified path
qc.raw.files <- tibble(filename = list.files(paste0(workingDirectory, folderQC), pattern = "*_QC.csv"))
mfi.raw.files <- tibble(filename = list.files(paste0(workingDirectory, folderMFI), pattern = "*_MFIs-unfiltered.csv"))

# remove the extensions from the file lists 
qc.raw.files.assays <- as.list(substr(qc.raw.files$filename, 1, nchar(qc.raw.files$filename)-7))
mfi.raw.files.assays <- as.list(substr(mfi.raw.files$filename, 1, nchar(mfi.raw.files$filename)-20))

# check to make sure there is an MFI file and a QC file for each assay
for (i in 1:length(mfi.raw.files.assays)){
  if (!(mfi.raw.files.assays[i] %in% qc.raw.files.assays)){
    stop(paste(mfi.raw.files[i,], "does not have an associated QC file"))
  }
}

for (i in 1:length(qc.raw.files.assays)){
  if (!(qc.raw.files.assays[i] %in% mfi.raw.files.assays)){
    stop(paste(qc.raw.files[i,], "does not have an associated MFI file"))
  }
}

# Step 2: Read in each QC file and perform initial QC check

# specify empty dataframes
qcpassfail <- setNames(data.frame(matrix(ncol = 4, nrow=0)), 
                       c("assay", "sampling_error", "blank_well_under_125"))

## for loop to check the overall metrics in all of the assays

for (i in (1:nrow(qc.raw.files))){
  # import QC data
  QCtest <- read_csv(paste0(workingDirectory, folderQC, qc.raw.files[i,]))
  
  assayqc <- c(qc.raw.files.assays[i])
  
  # for loop to make sure that the assay doesn't have sampling errors, that there 
  # are no high blank bead wells, and that the blank well is below 125
  if (!("No sampling errors" %in% QCtest$`sample type`)){
    assayqc <- append(assayqc, "FAIL")
  } else {
    assayqc <- append(assayqc, "PASS")
  }
  
  if (as.numeric(QCtest[(nrow(QCtest)-1), 3]) > 125 | as.numeric(QCtest[nrow(QCtest), 3]) > 125){
    assayqc <- append(assayqc, "FAIL")
  } else {
    assayqc <- append(assayqc, "PASS")
  }
  
  # bind the assay and pass/fail list to the overall dataframe
  qcpassfail <- rbind(qcpassfail, as.data.frame(assayqc, 
                                                col.names = c("assay", "sampling_error", "blank_well_under_125")))
}

# Step 3: Remove the assays that fail and put them into a separate dataframe
assaysPassedQC <- subset(qcpassfail, qcpassfail$sampling_error == "PASS" & qcpassfail$blank_well_under_125 == "PASS") 

# put assays that fail into a separate dataframe
assaysFailedQC <- anti_join(qcpassfail, assaysPassedQC)

# Step 4: Write out CSV with the assays included in the summary sheet
write.csv(assaysPassedQC, paste0(workingDirectory, folderOutput, projectName, "_assays-for-summary-sheet.csv"), row.names = FALSE)
write.csv(assaysFailedQC, paste0(workingDirectory, folderOutput, projectName, "_assays-excluded-for-summary-sheet.csv"), row.names = FALSE)



```

# Remove Samples that don't pass QC

```{r}

#---- Remove samples that don't pass QC ----

## create assay list
assaylist <- as.list(assaysPassedQC$assay)

# Initialize dataframes for each different category of file
QCfirstAD5 <- data.frame()
QCfirstAD4andAD5 <- data.frame()
QCfirstEverythingElse <- data.frame()
QCfirstGlycoprotein <- data.frame()
QCrerunsEverythingElse <- data.frame()
QCrerunsAD5 <- data.frame()
QCrerunsAD4andAD5 <- data.frame()
QCrerunsGlycoprotein <- data.frame()
QCrepeatsAD5 <- data.frame()
QCrepeatsAD4andAD5 <- data.frame()
QCrepeatsEverythingElse <- data.frame()
QCrepeatsGlycoprotein <- data.frame()
EE_AllPasses <- data.frame()
GP_AllPasses <-data.frame()
ad5_AllPasses <-data.frame()
ad4and5_AllPasses <-data.frame()
MasterFailedQCFile <- data.frame()
MasterSamplesPassedQCFile <- data.frame()
SummaryFile <- data.frame()

# Function to find column names with value over cvCutoff, excluding 'Reason' and 'sampledescription'
find_failed_beads <- function(row) {
  # Exclude 'Reason' and 'sampledescription'
  row <- row[!(names(row) %in% c("Reason", "sampledescription"))]
  failed_beads <- names(row)[row > cvCutoff]
  return(paste(failed_beads, collapse = ", "))
}

#Function to find column names with value over blankBeadCutoff
find_blank_bead_fails <- function(row) {
  # Exclude 'Reason' and 'sampledescription'
  row <- row[!(names(row) %in% c("Reason", "sampledescription"))]
  failed_beads <- names(row)[row > blankBeadCutoff]
  return(paste(failed_beads, collapse = ", "))
}

# Function to check for sampling errors
find_sampling_errors <- function(df) {
  # Check 'sample type' column for "No sampling errors"
  failed_samples <- df$`sample description`[df$`sample type` != "No sampling errors"]
  return(paste(failed_samples, collapse = ", "))
}

## for loop to combine all of the data that passes QC into one file, and all the ones that fail into another
for (i in (1:length(assaylist))){
  # Import QC data
  QCfile <- read_csv(paste0(workingDirectory, folderQC, assaylist[i], "_QC.csv"))
  
  # Condition that checks assay file by type, then reads data into the corresponding frames
  if ((grepl("EE", assaylist[i], ignore.case = TRUE)) & (grepl("repeats", assaylist[i], ignore.case = TRUE))) {
    # import QC data
    RepeatsEE_QCfile <- subset(QCfile, QCfile$id == "Low Bead Counts" | QCfile$id == "High %CVs")
    RepeatsEE_FailQC <- subset(RepeatsEE_QCfile, RepeatsEE_QCfile$`sample type` == "No high %CVs" | 
                           RepeatsEE_QCfile$`sample type` == "No low beadcounts" | 
                           RepeatsEE_QCfile$`sample type` == "No sampling errors")
    RepeatsEE_QCfile <- subset(RepeatsEE_QCfile, RepeatsEE_QCfile$`sample type` != "No high %CVs" & RepeatsEE_QCfile$`sample type` != "No low beadcounts")
    RepeatsEE_QCfile[] <- lapply(RepeatsEE_QCfile, as.character)
    RepeatsEE_QCfile <- RepeatsEE_QCfile[,-c(2,3)]
    RepeatsEE_QCfile <- dplyr::rename(RepeatsEE_QCfile, Reason = id)
    
    RepeatsEE_MFIfile <- read_csv(paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv"))
    RepeatsEE_PassedSamples <- anti_join(RepeatsEE_MFIfile, RepeatsEE_QCfile, by = c("sampledescription" = "sample description"))
    RepeatsEE_PassedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
    EE_AllPasses <- dplyr::bind_rows(EE_AllPasses, MasterSamplesPassedQCFile, RepeatsEE_PassedSamples)
    # Perform the inner join
    RepeatsEE_FailedSamples <- inner_join(RepeatsEE_MFIfile, RepeatsEE_QCfile, by = c("sampledescription" = "sample description"))
    
    RepeatsEE_FailedSamples <- RepeatsEE_FailedSamples %>%
      rename_with(~ gsub("\\.x$", " MFI", .x), ends_with(".x")) %>%
      rename_with(~ gsub("\\.y$", " %CV", .x), ends_with(".y"))
    
    # Find failed beads based on CV
    RepeatsEE_FailedSamples_CV <- RepeatsEE_FailedSamples[, grepl("CV$", names(RepeatsEE_FailedSamples))]
    RepeatsEE_FailedSamples$Failed_Beads <- apply(RepeatsEE_FailedSamples_CV, 1, find_failed_beads)
    
    # Find failed beads based on MFI
    RepeatsEE_FailedSamples_MFI <- RepeatsEE_FailedSamples[, grepl("MFI$", names(RepeatsEE_FailedSamples))]
    RepeatsEE_FailedSamples$Failed_Beads <- paste(RepeatsEE_FailedSamples$Failed_Beads, apply(RepeatsEE_FailedSamples_MFI, 1, find_blank_bead_fails), sep = ", ")
    
    
    # Add the 'assayfile' column
    RepeatsEE_FailedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
    
    # Rearrange the columns
    RepeatsEE_FailedSamples <- RepeatsEE_FailedSamples %>%
      dplyr::select(-Failed_Beads, -assayfile, Failed_Beads, assayfile)
    
    # creating a date column
    RepeatsEE_FailedDateList <- as.data.frame(RepeatsEE_FailedSamples$assayfile)
    RepeatsEE_AssayFailDate <- as.data.frame(RepeatsEE_FailedSamples$assayfile)
    colnames(RepeatsEE_FailedDateList) <- c("assayfile")
    RepeatsEE_FailedDateList <- RepeatsEE_FailedDateList %>%
      mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
      mutate(assayfile = str_remove(assayfile, folderMFI))
    RepeatsEE_FailedDateList$assayfile <- sub("_.*", "", RepeatsEE_FailedDateList$assayfile)
    
    # add date column to the fails sheet
    RepeatsEE_FailedSamples <- add_column(RepeatsEE_FailedSamples, RepeatsEE_FailedDateList$assayfile, .after = 1)
    
    # Rename the date column
    colnames(RepeatsEE_FailedSamples)[2] <- "Assay_Failed_Date_EE_repeats"
    
    # Rearrange the columns
    RepeatsEE_FailedSamples <- RepeatsEE_FailedSamples %>%
      dplyr::select(Assay_Failed_Date_EE_repeats, assayfile, Reason, Failed_Beads, everything())
    
    # Rename the assayfile column
    colnames(RepeatsEE_FailedSamples)[2] <- "raw_file_path_EE_2"
    
    # Append the rows of RepeatsEE_FailedSamples to QCrepeatsEverythingElse
    QCrepeatsEverythingElse <- merge(QCrepeatsEverythingElse, RepeatsEE_FailedSamples, all = TRUE)
  } else if ((grepl("GP", assaylist[i], ignore.case = TRUE)) & (grepl("repeats", assaylist[i], ignore.case = TRUE))) {
    # import QC data
    RepeatsGP_QCfile <- subset(QCfile, QCfile$id == "Low Bead Counts" | QCfile$id == "High %CVs")
    RepeatsGP_FailQC <- subset(RepeatsGP_QCfile, RepeatsGP_QCfile$`sample type` == "No high %CVs" | 
                           RepeatsGP_QCfile$`sample type` == "No low beadcounts" | 
                           RepeatsGP_QCfile$`sample type` == "No sampling errors")

    RepeatsGP_QCfile <- subset(RepeatsGP_QCfile, RepeatsGP_QCfile$`sample type` != "No high %CVs" & RepeatsGP_QCfile$`sample type` != "No low beadcounts")
    RepeatsGP_QCfile[] <- lapply(RepeatsGP_QCfile, as.character)
    RepeatsGP_QCfile <- RepeatsGP_QCfile[,-c(2,3)]
    RepeatsGP_QCfile <- dplyr::rename(RepeatsGP_QCfile, Reason = id)
    
    RepeatsGP_MFIfile <- read_csv(paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv"))
    RepeatsGP_PassedSamples <- anti_join(RepeatsGP_MFIfile, RepeatsGP_QCfile, by = c("sampledescription" = "sample description"))
    RepeatsGP_PassedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
    GP_AllPasses <- dplyr::bind_rows(GP_AllPasses, MasterSamplesPassedQCFile, RepeatsGP_PassedSamples)
    # Perform the inner join
    RepeatsGP_FailedSamples <- inner_join(RepeatsGP_MFIfile, RepeatsGP_QCfile, by = c("sampledescription" = "sample description"))
    
    RepeatsGP_FailedSamples <- RepeatsGP_FailedSamples %>%
      rename_with(~ gsub("\\.x$", " MFI", .x), ends_with(".x")) %>%
      rename_with(~ gsub("\\.y$", " %CV", .x), ends_with(".y"))
    
    # Find failed beads based on CV
    RepeatsGP_FailedSamples_CV <- RepeatsGP_FailedSamples[, grepl("CV$", names(RepeatsGP_FailedSamples))]
    RepeatsGP_FailedSamples$Failed_Beads <- apply(RepeatsGP_FailedSamples_CV, 1, find_failed_beads)
    
    # Find failed beads based on MFI
    RepeatsGP_FailedSamples_MFI <- RepeatsGP_FailedSamples[, grepl("MFI$", names(RepeatsGP_FailedSamples))]
    RepeatsGP_FailedSamples$Failed_Beads <- paste(RepeatsGP_FailedSamples$Failed_Beads, apply(RepeatsGP_FailedSamples_MFI, 1, find_blank_bead_fails), sep = ", ")
    
    
    # Add the 'assayfile' column
    RepeatsGP_FailedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
    
    # Rearrange the columns
    RepeatsGP_FailedSamples <- RepeatsGP_FailedSamples %>%
      dplyr::select(-Failed_Beads, -assayfile, Failed_Beads, assayfile)
    
    # creating a date column
    RepeatsGP_FailedDateList <- as.data.frame(RepeatsGP_FailedSamples$assayfile)
    RepeatsGP_AssayFailDate <- as.data.frame(RepeatsGP_FailedSamples$assayfile)
    colnames(RepeatsGP_FailedDateList) <- c("assayfile")
    RepeatsGP_FailedDateList <- RepeatsGP_FailedDateList %>%
      mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
      mutate(assayfile = str_remove(assayfile, folderMFI))
    RepeatsGP_FailedDateList$assayfile <- sub("_.*", "", RepeatsGP_FailedDateList$assayfile)
    
    # add date column to the fails sheet
    RepeatsGP_FailedSamples <- add_column(RepeatsGP_FailedSamples, RepeatsGP_FailedDateList$assayfile, .after = 1)
    
    # Rename the date column
    colnames(RepeatsGP_FailedSamples)[2] <- "Assay_Failed_Date_GP_repeats"
    
    # Rearrange the columns
    RepeatsGP_FailedSamples <- RepeatsGP_FailedSamples %>%
      dplyr::select(Assay_Failed_Date_GP_repeats, assayfile, Reason, Failed_Beads, everything())
    
    # Rename the assayfile column
    colnames(RepeatsGP_FailedSamples)[2] <- "raw_file_path_GP_2"
    
    # Append the rows of RepeatsGP_FailedSamples to QCrepeatsGlycoprotein
    QCrepeatsGlycoprotein <- rbind(QCrepeatsGlycoprotein, RepeatsGP_FailedSamples)
    
  } else if ((grepl("EE", assaylist[i], ignore.case = TRUE)) & (grepl("rerun", assaylist[i], ignore.case = TRUE))) {
    # import QC data
    RerunsEE_QCfile <- subset(QCfile, QCfile$id == "Low Bead Counts" | QCfile$id == "High %CVs")
    RerunsEE_FailQC <- subset(RerunsEE_QCfile, RerunsEE_QCfile$`sample type` == "No high %CVs" | 
                          RerunsEE_QCfile$`sample type` == "No low beadcounts" | 
                          RerunsEE_QCfile$`sample type` == "No sampling errors")
    RerunsEE_QCfile <- subset(RerunsEE_QCfile, RerunsEE_QCfile$`sample type` != "No high %CVs" & RerunsEE_QCfile$`sample type` != "No low beadcounts")
    RerunsEE_QCfile[] <- lapply(RerunsEE_QCfile, as.character)
    RerunsEE_QCfile <- RerunsEE_QCfile[,-c(2,3)]
    RerunsEE_QCfile <- dplyr::rename(RerunsEE_QCfile, Reason = id)
    
    RerunsEE_MFIfile <- read_csv(paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv"))
    RerunsEE_PassedSamples <- anti_join(RerunsEE_MFIfile, RerunsEE_QCfile, by = c("sampledescription" = "sample description"))
    RerunsEE_PassedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
    EE_AllPasses <- dplyr::bind_rows(EE_AllPasses,MasterSamplesPassedQCFile, RerunsEE_PassedSamples)
    # Perform the inner join
    RerunsEE_FailedSamples <- inner_join(RerunsEE_MFIfile, RerunsEE_QCfile, by = c("sampledescription" = "sample description"))
    
    RerunsEE_FailedSamples <- RerunsEE_FailedSamples %>%
      rename_with(~ gsub("\\.x$", " MFI", .x), ends_with(".x")) %>%
      rename_with(~ gsub("\\.y$", " %CV", .x), ends_with(".y"))
    
    # Find failed beads based on CV
    RerunsEE_FailedSamples_CV <- RerunsEE_FailedSamples[, grepl("CV$", names(RerunsEE_FailedSamples))]
    RerunsEE_FailedSamples$Failed_Beads <- apply(RerunsEE_FailedSamples_CV, 1, find_failed_beads)
    
    # Find failed beads based on MFI
    RerunsEE_FailedSamples_MFI <- RerunsEE_FailedSamples[, grepl("MFI$", names(RerunsEE_FailedSamples))]
    RerunsEE_FailedSamples$Failed_Beads <- paste(RerunsEE_FailedSamples$Failed_Beads, apply(RerunsEE_FailedSamples_MFI, 1, find_blank_bead_fails), sep = ", ")
    
    
    # Add the 'assayfile' column
    RerunsEE_FailedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
    
    # Rearrange the columns
    RerunsEE_FailedSamples <- RerunsEE_FailedSamples %>%
      dplyr::select(-Failed_Beads, -assayfile, Failed_Beads, assayfile)
    
    # creating a date column
    RerunsEE_FailedDateList <- as.data.frame(RerunsEE_FailedSamples$assayfile)
    RerunsEE_AssayFailDate <- as.data.frame(RerunsEE_FailedSamples$assayfile)
    colnames(RerunsEE_FailedDateList) <- c("assayfile")
    RerunsEE_FailedDateList <- RerunsEE_FailedDateList %>%
      mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
      mutate(assayfile = str_remove(assayfile, folderMFI))
    RerunsEE_FailedDateList$assayfile <- sub("_.*", "", RerunsEE_FailedDateList$assayfile)
    
    # add date column to the fails sheet
    RerunsEE_FailedSamples <- add_column(RerunsEE_FailedSamples, RerunsEE_FailedDateList$assayfile, .after = 1)
    
    # Rename the date column
    colnames(RerunsEE_FailedSamples)[2] <- "Assay_Failed_Date_EE_rerun"
    
    # Rearrange the columns
    RerunsEE_FailedSamples <- RerunsEE_FailedSamples %>%
      dplyr::select(Assay_Failed_Date_EE_rerun, assayfile, Reason, Failed_Beads, everything())
    
    # Rename the assayfile column
    colnames(RerunsEE_FailedSamples)[2] <- "raw_file_path_EE_1"
    
    # Append the rows of RerunsEE_FailedSamples to QCrerunsEverythingElse
    QCrerunsEverythingElse <- rbind(QCrerunsEverythingElse, RerunsEE_FailedSamples)
  } else if ((grepl("GP", assaylist[i], ignore.case = TRUE)) & (grepl("rerun", assaylist[i], ignore.case = TRUE))) {
    # import QC data
    RerunsGP_QCfile <- subset(QCfile, QCfile$id == "Low Bead Counts" | QCfile$id == "High %CVs")
    RerunsGP_FailQC <- subset(RerunsGP_QCfile, RerunsGP_QCfile$`sample type` == "No high %CVs" | 
                          RerunsGP_QCfile$`sample type` == "No low beadcounts" | 
                          RerunsGP_QCfile$`sample type` == "No sampling errors")
    RerunsGP_QCfile <- subset(RerunsGP_QCfile, RerunsGP_QCfile$`sample type` != "No high %CVs" & RerunsGP_QCfile$`sample type` != "No low beadcounts")
    RerunsGP_QCfile[] <- lapply(RerunsGP_QCfile, as.character)
    RerunsGP_QCfile <- RerunsGP_QCfile[,-c(2,3)]
    RerunsGP_QCfile <- dplyr::rename(RerunsGP_QCfile, Reason = id)
    
    RerunsGP_MFIfile <- read_csv(paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv"))
    RerunsGP_PassedSamples <- anti_join(RerunsGP_MFIfile, RerunsGP_QCfile, by = c("sampledescription" = "sample description"))
    RerunsGP_PassedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
    GP_AllPasses <- dplyr::bind_rows(GP_AllPasses, MasterSamplesPassedQCFile, RerunsGP_PassedSamples)
    # Perform the inner join
    RerunsGP_FailedSamples <- inner_join(RerunsGP_MFIfile, RerunsGP_QCfile, by = c("sampledescription" = "sample description"))
    
    RerunsGP_FailedSamples <- RerunsGP_FailedSamples %>%
      rename_with(~ gsub("\\.x$", " MFI", .x), ends_with(".x")) %>%
      rename_with(~ gsub("\\.y$", " %CV", .x), ends_with(".y"))
    
    # Find failed beads based on CV
    RerunsGP_FailedSamples_CV <- RerunsGP_FailedSamples[, grepl("CV$", names(RerunsGP_FailedSamples))]
    RerunsGP_FailedSamples$Failed_Beads <- apply(RerunsGP_FailedSamples_CV, 1, find_failed_beads)
    
    # Find failed beads based on MFI
    RerunsGP_FailedSamples_MFI <- RerunsGP_FailedSamples[, grepl("MFI$", names(RerunsGP_FailedSamples))]
    RerunsGP_FailedSamples$Failed_Beads <- paste(RerunsGP_FailedSamples$Failed_Beads, apply(RerunsGP_FailedSamples_MFI, 1, find_blank_bead_fails), sep = ", ")
    
    
    # Add the 'assayfile' column
    RerunsGP_FailedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
    
    # Rearrange the columns
    RerunsGP_FailedSamples <- RerunsGP_FailedSamples %>%
      dplyr::select(-Failed_Beads, -assayfile, Failed_Beads, assayfile)
    
    # creating a date column
    RerunsGP_FailedDateList <- as.data.frame(RerunsGP_FailedSamples$assayfile)
    RerunsGP_AssayFailDate <- as.data.frame(RerunsGP_FailedSamples$assayfile)
    colnames(RerunsGP_FailedDateList) <- c("assayfile")
    RerunsGP_FailedDateList <- RerunsGP_FailedDateList %>%
      mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
      mutate(assayfile = str_remove(assayfile, folderMFI))
    RerunsGP_FailedDateList$assayfile <- sub("_.*", "", RerunsGP_FailedDateList$assayfile)
    
    # add date column to the fails sheet
    RerunsGP_FailedSamples <- add_column(RerunsGP_FailedSamples, RerunsGP_FailedDateList$assayfile, .after = 1)
    
    # Rename the date column
    colnames(RerunsGP_FailedSamples)[2] <- "Assay_Failed_Date_GP_rerun"
    
    # Rearrange the columns
    RerunsGP_FailedSamples <- RerunsGP_FailedSamples %>%
      dplyr::select(Assay_Failed_Date_GP_rerun, assayfile, Reason, Failed_Beads, everything())
    
    # Rename the assayfile column
    colnames(RerunsGP_FailedSamples)[2] <- "raw_file_path_GP_1"
    
    # Append the rows of RerunsGP_FailedSamples to QCrerunsGlycoprotein
    QCrerunsGlycoprotein <- rbind(QCrerunsGlycoprotein, RerunsGP_FailedSamples)
  } else if ((grepl("GP", assaylist[i], ignore.case = TRUE) & 
             !grepl("reruns|repeats", assaylist[i], ignore.case = TRUE))){
    # import QC data
    GP_QCfile <- subset(QCfile, QCfile$id == "Low Bead Counts" | QCfile$id == "High %CVs")
    GP_FailQC <- subset(GP_QCfile, GP_QCfile$`sample type` == "No high %CVs" | 
                    GP_QCfile$`sample type` == "No low beadcounts" | 
                    GP_QCfile$`sample type` == "No sampling errors")
    GP_QCfile <- subset(GP_QCfile, GP_QCfile$`sample type` != "No high %CVs" & GP_QCfile$`sample type` != "No low beadcounts")
    GP_QCfile[] <- lapply(GP_QCfile, as.character)
    GP_QCfile <- GP_QCfile[,-c(2,3)]
    GP_QCfile <- dplyr::rename(GP_QCfile, Reason = id)
    
    GP_MFIfile <- read_csv(paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv"))
    GP_PassedSamples <- anti_join(GP_MFIfile, GP_QCfile, by = c("sampledescription" = "sample description"))
    GP_PassedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
    GP_AllPasses <- dplyr::bind_rows(GP_AllPasses, MasterSamplesPassedQCFile, GP_PassedSamples)
    # Perform the inner join
    GP_FailedSamples <- inner_join(GP_MFIfile, GP_QCfile, by = c("sampledescription" = "sample description"))
    
    GP_FailedSamples <- GP_FailedSamples %>%
      rename_with(~ gsub("\\.x$", " MFI", .x), ends_with(".x")) %>%
      rename_with(~ gsub("\\.y$", " %CV", .x), ends_with(".y"))
    
    # Find failed beads based on CV
    GP_FailedSamples_CV <- GP_FailedSamples[, grepl("CV$", names(GP_FailedSamples))]
    GP_FailedSamples$Failed_Beads <- apply(GP_FailedSamples_CV, 1, find_failed_beads)
    
    # Find failed beads based on MFI
    GP_FailedSamples_MFI <- GP_FailedSamples[, grepl("MFI$", names(GP_FailedSamples))]
    GP_FailedSamples$Failed_Beads <- paste(GP_FailedSamples$Failed_Beads, apply(GP_FailedSamples_MFI, 1, find_blank_bead_fails), sep = ", ")
    
    
    # Add the 'assayfile' column
    GP_FailedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
    
    # Rearrange the columns
    GP_FailedSamples <- GP_FailedSamples %>%
      dplyr::select(-Failed_Beads,-assayfile,Failed_Beads,assayfile)
    
    # creating a date column
    GP_FailedDateList <- as.data.frame(GP_FailedSamples$assayfile)
    GP_AssayFailDate <- as.data.frame(GP_FailedSamples$assayfile)
    colnames(GP_FailedDateList) <- c("assayfile")
    GP_FailedDateList <- GP_FailedDateList %>%
      mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
      mutate(assayfile = str_remove(assayfile, folderMFI))
    GP_FailedDateList$assayfile <- sub("_.*", "", GP_FailedDateList$assayfile)
    
    # add date column to the fails sheet
    GP_FailedSamples <- add_column(GP_FailedSamples, GP_FailedDateList$assayfile, .after = 1)
    
    # Rename the date column
    colnames(GP_FailedSamples)[2] <- "Assay_Failed_Date_GP"
    
    # Rearrange the columns
    GP_FailedSamples <- GP_FailedSamples %>%
      dplyr::select(Assay_Failed_Date_GP, assayfile, Reason, Failed_Beads, everything())
    
    # Rename the assayfile column
    colnames(GP_FailedSamples)[2] <- "raw_file_path_GP"
    
    # Append the rows of GP_FailedSamples to QCfirstGlycoprotein
    QCfirstGlycoprotein <- rbind(QCfirstGlycoprotein, GP_FailedSamples)
  } else if ((grepl("EE", assaylist[i], ignore.case = TRUE) & 
             !grepl("reruns|repeats", assaylist[i], ignore.case = TRUE))){
    
    # import QC data
    EE_QCfile <- subset(QCfile, QCfile$id == "Low Bead Counts" | QCfile$id == "High %CVs")
    EE_FailQC <- subset(EE_QCfile, EE_QCfile$`sample type` == "No high %CVs" | 
                    EE_QCfile$`sample type` == "No low beadcounts" | 
                    EE_QCfile$`sample type` == "No sampling errors")
    EE_QCfile <- subset(EE_QCfile, EE_QCfile$`sample type` != "No high %CVs" & EE_QCfile$`sample type` != "No low beadcounts")
    EE_QCfile[] <- lapply(EE_QCfile, as.character)
    EE_QCfile <- EE_QCfile[,-c(2,3)]
    EE_QCfile <- dplyr::rename(EE_QCfile, Reason = id)
    
    EE_MFIfile <- read_csv(paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv"))
    EE_PassedSamples <- anti_join(EE_MFIfile, EE_QCfile, by = c("sampledescription" = "sample description"))
    EE_PassedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
    EE_AllPasses <- dplyr::bind_rows(EE_AllPasses, MasterSamplesPassedQCFile, EE_PassedSamples)
    # Perform the inner join
    EE_FailedSamples <- inner_join(EE_MFIfile, EE_QCfile, by = c("sampledescription" = "sample description"))
    
    # Rename the columns
    EE_FailedSamples <- EE_FailedSamples %>%
      rename_with(~ gsub("\\.x$", " MFI", .x), ends_with(".x")) %>%
      rename_with(~ gsub("\\.y$", " %CV", .x), ends_with(".y"))
    
    # Find failed beads based on CV
    EE_FailedSamples_CV <- EE_FailedSamples[, grepl("CV$", names(EE_FailedSamples))]
    EE_FailedSamples$Failed_Beads <- apply(EE_FailedSamples_CV, 1, find_failed_beads)
    
    # Find failed beads based on MFI
    EE_FailedSamples_MFI <- EE_FailedSamples[, grepl("MFI$", names(EE_FailedSamples))]
    EE_FailedSamples$Failed_Beads <- paste(EE_FailedSamples$Failed_Beads, apply(EE_FailedSamples_MFI, 1, find_blank_bead_fails), sep = ", ")
    
    
    # Add the 'assayfile' column
    EE_FailedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
    
    # Rearrange the columns
    EE_FailedSamples <- EE_FailedSamples %>%
      dplyr::select(-Failed_Beads, -assayfile, Failed_Beads, assayfile)
    
    # creating a date column
    EE_FailedDateList <- as.data.frame(EE_FailedSamples$assayfile)
    EE_AssayFailDate <- as.data.frame(EE_FailedSamples$assayfile)
    colnames(EE_FailedDateList) <- c("assayfile")
    EE_FailedDateList <- EE_FailedDateList %>%
      mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
      mutate(assayfile = str_remove(assayfile, folderMFI))
    EE_FailedDateList$assayfile <- sub("_.*", "", EE_FailedDateList$assayfile)
    
    # add date column to the fails sheet
    EE_FailedSamples <- add_column(EE_FailedSamples, EE_FailedDateList$assayfile, .after = 1)
    
    # Rename the date column
    colnames(EE_FailedSamples)[2] <- "Assay_Failed_Date_EE"
    
    # Rearrange the columns
    EE_FailedSamples <- EE_FailedSamples %>%
      dplyr::select(Assay_Failed_Date_EE, assayfile, Reason, Failed_Beads, everything())
    
    # Rename the assayfile column
    colnames(EE_FailedSamples)[2] <- "raw_file_path_EE"
    
    # Append the rows of EE_FailedSamples to QCfirstEverythingElse
    QCfirstEverythingElse <- merge(QCfirstEverythingElse, EE_FailedSamples, all = TRUE)
  } else if ((grepl("ad5", assaylist[i], ignore.case = TRUE) & 
          !grepl("reruns|repeats", assaylist[i], ignore.case = TRUE))) {
  # Handle the "ad5" naming convention

  # Import QC data for "ad5"
  ad5_QCfile <- subset(QCfile, QCfile$id == "Low Bead Counts" | QCfile$id == "High %CVs")
  ad5_FailQC <- subset(ad5_QCfile, ad5_QCfile$`sample type` == "No high %CVs" | 
                     ad5_QCfile$`sample type` == "No low beadcounts" | 
                     ad5_QCfile$`sample type` == "No sampling errors")
  ad5_QCfile <- subset(ad5_QCfile, ad5_QCfile$`sample type` != "No high %CVs" & ad5_QCfile$`sample type` != "No low beadcounts")
  ad5_QCfile[] <- lapply(ad5_QCfile, as.character)
  ad5_QCfile <- ad5_QCfile[,-c(2,3)]
  ad5_QCfile <- dplyr::rename(ad5_QCfile, Reason = id)

  ad5_MFIfile <- read_csv(paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv"))
  ad5_PassedSamples <- anti_join(ad5_MFIfile, ad5_QCfile, by = c("sampledescription" = "sample description"))
  ad5_PassedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
  ad5_AllPasses <- dplyr::bind_rows(ad5_AllPasses, MasterSamplesPassedQCFile, ad5_PassedSamples)
  # Perform the inner join
  ad5_FailedSamples <- inner_join(ad5_MFIfile, ad5_QCfile, by = c("sampledescription" = "sample description"))

  # Rename the columns
  ad5_FailedSamples <- ad5_FailedSamples %>%
    rename_with(~ gsub("\\.x$", " MFI", .x), ends_with(".x")) %>%
    rename_with(~ gsub("\\.y$", " %CV", .x), ends_with(".y"))

  # Find failed beads based on CV
  ad5_FailedSamples_CV <- ad5_FailedSamples[, grepl("CV$", names(ad5_FailedSamples))]
  ad5_FailedSamples$Failed_Beads <- apply(ad5_FailedSamples_CV, 1, find_failed_beads)

  # Find failed beads based on MFI
  ad5_FailedSamples_MFI <- ad5_FailedSamples[, grepl("MFI$", names(ad5_FailedSamples))]
  ad5_FailedSamples$Failed_Beads <- paste(ad5_FailedSamples$Failed_Beads, apply(ad5_FailedSamples_MFI, 1, find_blank_bead_fails), sep = ", ")

  # Add the 'assayfile' column
  ad5_FailedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")

  # Rearrange the columns
  ad5_FailedSamples <- ad5_FailedSamples %>%
    dplyr::select(-Failed_Beads, -assayfile, Failed_Beads, assayfile)

  # Creating a date column
  ad5_FailedDateList <- as.data.frame(ad5_FailedSamples$assayfile)
  colnames(ad5_FailedDateList) <- c("assayfile")
  ad5_FailedDateList <- ad5_FailedDateList %>%
    mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
    mutate(assayfile = str_remove(assayfile, folderMFI))
  ad5_FailedDateList$assayfile <- sub("_.*", "", ad5_FailedDateList$assayfile)

  # Add date column to the fails sheet
  ad5_FailedSamples <- add_column(ad5_FailedSamples, ad5_FailedDateList$assayfile, .after = 1)

  # Rename the date column
  colnames(ad5_FailedSamples)[2] <- "Assay_Failed_Date_ad5"

  # Rearrange the columns
  ad5_FailedSamples <- ad5_FailedSamples %>%
    dplyr::select(Assay_Failed_Date_ad5, assayfile, Reason, Failed_Beads, everything())

  # Rename the assayfile column
  colnames(ad5_FailedSamples)[2] <- "raw_file_path_ad5"

  # Append the rows of "ad5" FailedSamples to QCfirstEverythingElse
  QCfirstAD5 <- merge(QCfirstAD5, ad5_FailedSamples, all = TRUE)
  } else if ((grepl("ad5", assaylist[i], ignore.case = TRUE) & 
          grepl("repeats", assaylist[i], ignore.case = TRUE))) {
  # Handle the "ad5" naming convention for repeats

  # Import QC data for "ad5Repeats"
  ad5Repeats_QCfile <- subset(QCfile, QCfile$id == "Low Bead Counts" | QCfile$id == "High %CVs")
  ad5Repeats_FailQC <- subset(ad5Repeats_QCfile, ad5Repeats_QCfile$`sample type` == "No high %CVs" | ad5Repeats_QCfile$`sample type` == "No low beadcounts")
  ad5Repeats_QCfile <- subset(ad5Repeats_QCfile, ad5Repeats_QCfile$`sample type` != "No high %CVs" & ad5Repeats_QCfile$`sample type` != "No low beadcounts")
  ad5Repeats_QCfile[] <- lapply(ad5Repeats_QCfile, as.character)
  ad5Repeats_QCfile <- ad5Repeats_QCfile[,-c(2,3)]
  ad5Repeats_QCfile <- dplyr::rename(ad5Repeats_QCfile, Reason = id)

  ad5Repeats_MFIfile <- read_csv(paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv"))
  ad5Repeats_PassedSamples <- anti_join(ad5Repeats_MFIfile, ad5Repeats_QCfile, by = c("sampledescription" = "sample description"))
  ad5Repeats_PassedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
  ad5Repeats_AllPasses <- dplyr::bind_rows(ad5Repeats_AllPasses, MasterSamplesPassedQCFile, ad5Repeats_PassedSamples)
  # Perform the inner join
  ad5Repeats_FailedSamples <- inner_join(ad5Repeats_MFIfile, ad5Repeats_QCfile, by = c("sampledescription" = "sample description"))

  # Rename the columns
  ad5Repeats_FailedSamples <- ad5Repeats_FailedSamples %>%
    rename_with(~ gsub("\\.x$", " MFI", .x), ends_with(".x")) %>%
    rename_with(~ gsub("\\.y$", " %CV", .x), ends_with(".y"))

  # Find failed beads based on CV
  ad5Repeats_FailedSamples_CV <- ad5Repeats_FailedSamples[, grepl("CV$", names(ad5Repeats_FailedSamples))]
  ad5Repeats_FailedSamples$Failed_Beads <- apply(ad5Repeats_FailedSamples_CV, 1, find_failed_beads)

  # Find failed beads based on MFI
  ad5Repeats_FailedSamples_MFI <- ad5Repeats_FailedSamples[, grepl("MFI$", names(ad5Repeats_FailedSamples))]
  ad5Repeats_FailedSamples$Failed_Beads <- paste(ad5Repeats_FailedSamples$Failed_Beads, apply(ad5Repeats_FailedSamples_MFI, 1, find_blank_bead_fails), sep = ", ")

  # Add the 'assayfile' column
  ad5Repeats_FailedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")

  # Rearrange the columns
  ad5Repeats_FailedSamples <- ad5Repeats_FailedSamples %>%
    dplyr::select(-Failed_Beads, -assayfile, Failed_Beads, assayfile)

  # Creating a date column
  ad5Repeats_FailedDateList <- as.data.frame(ad5Repeats_FailedSamples$assayfile)
  colnames(ad5Repeats_FailedDateList) <- c("assayfile")
  ad5Repeats_FailedDateList <- ad5Repeats_FailedDateList %>%
    mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
    mutate(assayfile = str_remove(assayfile, folderMFI))
  ad5Repeats_FailedDateList$assayfile <- sub("_.*", "", ad5Repeats_FailedDateList$assayfile)

  # Add date column to the fails sheet
  ad5Repeats_FailedSamples <- add_column(ad5Repeats_FailedSamples, ad5Repeats_FailedDateList$assayfile, .after = 1)

  # Rename the date column
  colnames(ad5Repeats_FailedSamples)[2] <- "Assay_Failed_Date_ad5Repeats"

  # Rearrange the columns
  ad5Repeats_FailedSamples <- ad5Repeats_FailedSamples %>%
    dplyr::select(Assay_Failed_Date_ad5Repeats, assayfile, Reason, Failed_Beads, everything())

  # Rename the assayfile column
  colnames(ad5Repeats_FailedSamples)[2] <- "raw_file_path_ad5Repeats"

  # Append the rows of "ad5Repeats" FailedSamples to QCfirstEverythingElse
  QCrepeatsAD5 <- merge(QCrepeatsAD5, ad5Repeats_FailedSamples, all = TRUE)
  } else if ((grepl("ad5", assaylist[i], ignore.case = TRUE) & 
          grepl("reruns", assaylist[i], ignore.case = TRUE))) {
  # Handle the "ad5Reruns" naming convention

  # Import QC data for "ad5Reruns"
  ad5Reruns_QCfile <- subset(QCfile, QCfile$id == "Low Bead Counts" | QCfile$id == "High %CVs")
  ad5Reruns_FailQC <- subset(ad5Reruns_QCfile, ad5Reruns_QCfile$`sample type` == "No high %CVs" | 
                           ad5Reruns_QCfile$`sample type` == "No low beadcounts" | 
                           ad5Reruns_QCfile$`sample type` == "No sampling errors")
  ad5Reruns_QCfile <- subset(ad5Reruns_QCfile, ad5Reruns_QCfile$`sample type` != "No high %CVs" & ad5Reruns_QCfile$`sample type` != "No low beadcounts")
  ad5Reruns_QCfile[] <- lapply(ad5Reruns_QCfile, as.character)
  ad5Reruns_QCfile <- ad5Reruns_QCfile[,-c(2,3)]
  ad5Reruns_QCfile <- dplyr::rename(ad5Reruns_QCfile, Reason = id)

  ad5Reruns_MFIfile <- read_csv(paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv"))
  ad5Reruns_PassedSamples <- anti_join(ad5Reruns_MFIfile, ad5Reruns_QCfile, by = c("sampledescription" = "sample description"))
  ad5Reruns_PassedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
  ad5Reruns_AllPasses <- dplyr::bind_rows(ad5Reruns_AllPasses, MasterSamplesPassedQCFile, ad5Reruns_PassedSamples)
  # Perform the inner join
  ad5Reruns_FailedSamples <- inner_join(ad5Reruns_MFIfile, ad5Reruns_QCfile, by = c("sampledescription" = "sample description"))

  # Rename the columns
  ad5Reruns_FailedSamples <- ad5Reruns_FailedSamples %>%
    rename_with(~ gsub("\\.x$", " MFI", .x), ends_with(".x")) %>%
    rename_with(~ gsub("\\.y$", " %CV", .x), ends_with(".y"))

  # Find failed beads based on CV
  ad5Reruns_FailedSamples_CV <- ad5Reruns_FailedSamples[, grepl("CV$", names(ad5Reruns_FailedSamples))]
  ad5Reruns_FailedSamples$Failed_Beads <- apply(ad5Reruns_FailedSamples_CV, 1, find_failed_beads)

  # Find failed beads based on MFI
  ad5Reruns_FailedSamples_MFI <- ad5Reruns_FailedSamples[, grepl("MFI$", names(ad5Reruns_FailedSamples))]
  ad5Reruns_FailedSamples$Failed_Beads <- paste(ad5Reruns_FailedSamples$Failed_Beads, apply(ad5Reruns_FailedSamples_MFI, 1, find_blank_bead_fails), sep = ", ")

  # Add the 'assayfile' column
  ad5Reruns_FailedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")

  # Rearrange the columns
  ad5Reruns_FailedSamples <- ad5Reruns_FailedSamples %>%
    dplyr::select(-Failed_Beads, -assayfile, Failed_Beads, assayfile)

  # Creating a date column
  ad5Reruns_FailedDateList <- as.data.frame(ad5Reruns_FailedSamples$assayfile)
  colnames(ad5Reruns_FailedDateList) <- c("assayfile")
  ad5Reruns_FailedDateList <- ad5Reruns_FailedDateList %>%
    mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
    mutate(assayfile = str_remove(assayfile, folderMFI))
  ad5Reruns_FailedDateList$assayfile <- sub("_.*", "", ad5Reruns_FailedDateList$assayfile)

  # Add date column to the fails sheet
  ad5Reruns_FailedSamples <- add_column(ad5Reruns_FailedSamples, ad5Reruns_FailedDateList$assayfile, .after = 1)

  # Rename the date column
  colnames(ad5Reruns_FailedSamples)[2] <- "Assay_Failed_Date_ad5Reruns"

  # Rearrange the columns
  ad5Reruns_FailedSamples <- ad5Reruns_FailedSamples %>%
    dplyr::select(Assay_Failed_Date_ad5Reruns, assayfile, Reason, Failed_Beads, everything())

  # Rename the assayfile column
  colnames(ad5Reruns_FailedSamples)[2] <- "raw_file_path_ad5Reruns"

  # Append the rows of "ad5Reruns" FailedSamples to QCfirstEverythingElse
  QCrerunsAD5 <- merge(QCrerunsAD5, ad5Reruns_FailedSamples, all = TRUE)
  } else if ((grepl("ad4and5", assaylist[i], ignore.case = TRUE) & 
          !grepl("reruns|repeats", assaylist[i], ignore.case = TRUE))) {
  # Handle the "ad4and5" naming convention

  # Import QC data for "ad4and5"
  ad4and5_QCfile <- subset(QCfile, QCfile$id == "Low Bead Counts" | QCfile$id == "High %CVs")
  ad4and5_FailQC <- subset(ad4and5_QCfile, ad4and5_QCfile$`sample type` == "No high %CVs" | 
                         ad4and5_QCfile$`sample type` == "No low beadcounts" | 
                         ad4and5_QCfile$`sample type` == "No sampling errors")
  ad4and5_QCfile <- subset(ad4and5_QCfile, ad4and5_QCfile$`sample type` != "No high %CVs" & ad4and5_QCfile$`sample type` != "No low beadcounts")
  ad4and5_QCfile[] <- lapply(ad4and5_QCfile, as.character)
  ad4and5_QCfile <- ad4and5_QCfile[,-c(2,3)]
  ad4and5_QCfile <- dplyr::rename(ad4and5_QCfile, Reason = id)

  ad4and5_MFIfile <- read_csv(paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv"))
  ad4and5_PassedSamples <- anti_join(ad4and5_MFIfile, ad4and5_QCfile, by = c("sampledescription" = "sample description"))
  ad4and5_PassedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
  ad4and5_AllPasses <- dplyr::bind_rows(ad4and5_AllPasses, MasterSamplesPassedQCFile, ad4and5_PassedSamples)
  # Perform the inner join
  ad4and5_FailedSamples <- inner_join(ad4and5_MFIfile, ad4and5_QCfile, by = c("sampledescription" = "sample description"))

  # Rename the columns
  ad4and5_FailedSamples <- ad4and5_FailedSamples %>%
    rename_with(~ gsub("\\.x$", " MFI", .x), ends_with(".x")) %>%
    rename_with(~ gsub("\\.y$", " %CV", .x), ends_with(".y"))

  # Find failed beads based on CV
  ad4and5_FailedSamples_CV <- ad4and5_FailedSamples[, grepl("CV$", names(ad4and5_FailedSamples))]
  ad4and5_FailedSamples$Failed_Beads <- apply(ad4and5_FailedSamples_CV, 1, find_failed_beads)

  # Find failed beads based on MFI
  ad4and5_FailedSamples_MFI <- ad4and5_FailedSamples[, grepl("MFI$", names(ad4and5_FailedSamples))]
  ad4and5_FailedSamples$Failed_Beads <- paste(ad4and5_FailedSamples$Failed_Beads, apply(ad4and5_FailedSamples_MFI, 1, find_blank_bead_fails), sep = ", ")

  # Add the 'assayfile' column
  ad4and5_FailedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")

  # Rearrange the columns
  ad4and5_FailedSamples <- ad4and5_FailedSamples %>%
    dplyr::select(-Failed_Beads, -assayfile, Failed_Beads, assayfile)

  # Creating a date column
  ad4and5_FailedDateList <- as.data.frame(ad4and5_FailedSamples$assayfile)
  colnames(ad4and5_FailedDateList) <- c("assayfile")
  ad4and5_FailedDateList <- ad4and5_FailedDateList %>%
    mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
    mutate(assayfile = str_remove(assayfile, folderMFI))
  ad4and5_FailedDateList$assayfile <- sub("_.*", "", ad4and5_FailedDateList$assayfile)

  # Add date column to the fails sheet
  ad4and5_FailedSamples <- add_column(ad4and5_FailedSamples, ad4and5_FailedDateList$assayfile, .after = 1)

  # Rename the date column
  colnames(ad4and5_FailedSamples)[2] <- "Assay_Failed_Date_ad4and5"

  # Rearrange the columns
  ad4and5_FailedSamples <- ad4and5_FailedSamples %>%
    dplyr::select(Assay_Failed_Date_ad4and5, assayfile, Reason, Failed_Beads, everything())

  # Rename the assayfile column
  colnames(ad4and5_FailedSamples)[2] <- "raw_file_path_ad4and5"

  # Append the rows of "ad4and5" FailedSamples to QCfirstEverythingElse
  QCfirstAD4and5 <- merge(QCfirstAD4and5, ad4and5_FailedSamples, all = TRUE)
    } else if ((grepl("ad4and5", assaylist[i], ignore.case = TRUE) & 
          grepl("reruns", assaylist[i], ignore.case = TRUE))) {
  # Handle the "ad4and5Reruns" naming convention

  # Import QC data for "ad4and5Reruns"
  ad4and5Reruns_QCfile <- subset(QCfile, QCfile$id == "Low Bead Counts" | QCfile$id == "High %CVs")
  ad4and5Reruns_FailQC <- subset(ad4and5Reruns_QCfile, ad4and5Reruns_QCfile$`sample type` == "No high %CVs" | 
                               ad4and5Reruns_QCfile$`sample type` == "No low beadcounts" | 
                               ad4and5Reruns_QCfile$`sample type` == "No sampling errors")
  ad4and5Reruns_QCfile <- subset(ad4and5Reruns_QCfile, ad4and5Reruns_QCfile$`sample type` != "No high %CVs" & ad4and5Reruns_QCfile$`sample type` != "No low beadcounts")
  ad4and5Reruns_QCfile[] <- lapply(ad4and5Reruns_QCfile, as.character)
  ad4and5Reruns_QCfile <- ad4and5Reruns_QCfile[,-c(2,3)]
  ad4and5Reruns_QCfile <- dplyr::rename(ad4and5Reruns_QCfile, Reason = id)

  ad4and5Reruns_MFIfile <- read_csv(paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv"))
  ad4and5Reruns_PassedSamples <- anti_join(ad4and5Reruns_MFIfile, ad4and5Reruns_QCfile, by = c("sampledescription" = "sample description"))
  ad4and5Reruns_PassedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
  ad4and5Reruns_AllPasses <- dplyr::bind_rows(ad4and5Reruns_AllPasses, MasterSamplesPassedQCFile, ad4and5Reruns_PassedSamples)
  # Perform the inner join
  ad4and5Reruns_FailedSamples <- inner_join(ad4and5Reruns_MFIfile, ad4and5Reruns_QCfile, by = c("sampledescription" = "sample description"))

  # Rename the columns
  ad4and5Reruns_FailedSamples <- ad4and5Reruns_FailedSamples %>%
    rename_with(~ gsub("\\.x$", " MFI", .x), ends_with(".x")) %>%
    rename_with(~ gsub("\\.y$", " %CV", .x), ends_with(".y"))

  # Find failed beads based on CV
  ad4and5Reruns_FailedSamples_CV <- ad4and5Reruns_FailedSamples[, grepl("CV$", names(ad4and5Reruns_FailedSamples))]
  ad4and5Reruns_FailedSamples$Failed_Beads <- apply(ad4and5Reruns_FailedSamples_CV, 1, find_failed_beads)

  # Find failed beads based on MFI
  ad4and5Reruns_FailedSamples_MFI <- ad4and5Reruns_FailedSamples[, grepl("MFI$", names(ad4and5Reruns_FailedSamples))]
  ad4and5Reruns_FailedSamples$Failed_Beads <- paste(ad4and5Reruns_FailedSamples$Failed_Beads, apply(ad4and5Reruns_FailedSamples_MFI, 1, find_blank_bead_fails), sep = ", ")

  # Add the 'assayfile' column
  ad4and5Reruns_FailedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")

  # Rearrange the columns
  ad4and5Reruns_FailedSamples <- ad4and5Reruns_FailedSamples %>%
    dplyr::select(-Failed_Beads, -assayfile, Failed_Beads, assayfile)

  # Creating a date column
  ad4and5Reruns_FailedDateList <- as.data.frame(ad4and5Reruns_FailedSamples$assayfile)
  colnames(ad4and5Reruns_FailedDateList) <- c("assayfile")
  ad4and5Reruns_FailedDateList <- ad4and5Reruns_FailedDateList %>%
    mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
    mutate(assayfile = str_remove(assayfile, folderMFI))
  ad4and5Reruns_FailedDateList$assayfile <- sub("_.*", "", ad4and5Reruns_FailedDateList$assayfile)

  # Add date column to the fails sheet
  ad4and5Reruns_FailedSamples <- add_column(ad4and5Reruns_FailedSamples, ad4and5Reruns_FailedDateList$assayfile, .after = 1)

  # Rename the date column
  colnames(ad4and5Reruns_FailedSamples)[2] <- "Assay_Failed_Date_ad4and5Reruns"

  # Rearrange the columns
  ad4and5Reruns_FailedSamples <- ad4and5Reruns_FailedSamples %>%
    dplyr::select(Assay_Failed_Date_ad4and5Reruns, assayfile, Reason, Failed_Beads, everything())

  # Rename the assayfile column
  colnames(ad4and5Reruns_FailedSamples)[2] <- "raw_file_path_ad4and5Reruns"

  # Append the rows of "ad4and5Reruns" FailedSamples to QCfirstEverythingElse
  QCrerunsAD4and5 <- merge(QCrerunsAD4and5, ad4and5Reruns_FailedSamples, all = TRUE)
    } else if ((grepl("ad4and5", assaylist[i], ignore.case = TRUE) & 
          grepl("repeats", assaylist[i], ignore.case = TRUE))) {
  # Handle the "ad4and5Repeats" naming convention

  # Import QC data for "ad4and5Repeats"
  ad4and5Repeats_QCfile <- subset(QCfile, QCfile$id == "Low Bead Counts" | QCfile$id == "High %CVs")
  ad4and5Repeats_FailQC <- subset(ad4and5Repeats_QCfile, ad4and5Repeats_QCfile$`sample type` == "No high %CVs" | 
                                ad4and5Repeats_QCfile$`sample type` == "No low beadcounts" | 
                                ad4and5Repeats_QCfile$`sample type` == "No sampling errors")
  ad4and5Repeats_QCfile <- subset(ad4and5Repeats_QCfile, ad4and5Repeats_QCfile$`sample type` != "No high %CVs" & ad4and5Repeats_QCfile$`sample type` != "No low beadcounts")
  ad4and5Repeats_QCfile[] <- lapply(ad4and5Repeats_QCfile, as.character)
  ad4and5Repeats_QCfile <- ad4and5Repeats_QCfile[,-c(2,3)]
  ad4and5Repeats_QCfile <- dplyr::rename(ad4and5Repeats_QCfile, Reason = id)

  ad4and5Repeats_MFIfile <- read_csv(paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv"))
  ad4and5Repeats_PassedSamples <- anti_join(ad4and5Repeats_MFIfile, ad4and5Repeats_QCfile, by = c("sampledescription" = "sample description"))
  ad4and5Repeats_PassedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")
  ad4and5Repeats_AllPasses <- dplyr::bind_rows(ad4and5Repeats_AllPasses, MasterSamplesPassedQCFile, ad4and5Repeats_PassedSamples)
  # Perform the inner join
  ad4and5Repeats_FailedSamples <- inner_join(ad4and5Repeats_MFIfile, ad4and5Repeats_QCfile, by = c("sampledescription" = "sample description"))

  # Rename the columns
  ad4and5Repeats_FailedSamples <- ad4and5Repeats_FailedSamples %>%
    rename_with(~ gsub("\\.x$", " MFI", .x), ends_with(".x")) %>%
    rename_with(~ gsub("\\.y$", " %CV", .x), ends_with(".y"))

  # Find failed beads based on CV
  ad4and5Repeats_FailedSamples_CV <- ad4and5Repeats_FailedSamples[, grepl("CV$", names(ad4and5Repeats_FailedSamples))]
  ad4and5Repeats_FailedSamples$Failed_Beads <- apply(ad4and5Repeats_FailedSamples_CV, 1, find_failed_beads)

  # Find failed beads based on MFI
  ad4and5Repeats_FailedSamples_MFI <- ad4and5Repeats_FailedSamples[, grepl("MFI$", names(ad4and5Repeats_FailedSamples))]
  ad4and5Repeats_FailedSamples$Failed_Beads <- paste(ad4and5Repeats_FailedSamples$Failed_Beads, apply(ad4and5Repeats_FailedSamples_MFI, 1, find_blank_bead_fails), sep = ", ")

  # Add the 'assayfile' column
  ad4and5Repeats_FailedSamples$assayfile <- paste0(workingDirectory, folderMFI, assaylist[i], "_MFIs-unfiltered.csv")

  # Rearrange the columns
  ad4and5Repeats_FailedSamples <- ad4and5Repeats_FailedSamples %>%
    dplyr::select(-Failed_Beads, -assayfile, Failed_Beads, assayfile)

  # Creating a date column
  ad4and5Repeats_FailedDateList <- as.data.frame(ad4and5Repeats_FailedSamples$assayfile)
  colnames(ad4and5Repeats_FailedDateList) <- c("assayfile")
  ad4and5Repeats_FailedDateList <- ad4and5Repeats_FailedDateList %>%
    mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
    mutate(assayfile = str_remove(assayfile, folderMFI))
  ad4and5Repeats_FailedDateList$assayfile <- sub("_.*", "", ad4and5Repeats_FailedDateList$assayfile)

  # Add date column to the fails sheet
  ad4and5Repeats_FailedSamples <- add_column(ad4and5Repeats_FailedSamples, ad4and5Repeats_FailedDateList$assayfile, .after = 1)

  # Rename the date column
  colnames(ad4and5Repeats_FailedSamples)[2] <- "Assay_Failed_Date_ad4and5Repeats"

  # Rearrange the columns
  ad4and5Repeats_FailedSamples <- ad4and5Repeats_FailedSamples %>%
    dplyr::select(Assay_Failed_Date_ad4and5Repeats, assayfile, Reason, Failed_Beads, everything())

  # Rename the assayfile column
  colnames(ad4and5Repeats_FailedSamples)[2] <- "raw_file_path_ad4and5Repeats"

  # Append the rows of "ad4and5Repeats" FailedSamples to QCfirstEverythingElse
  QCrepeatsAD4and5 <- merge(QCrepeatsAD4and5, ad4and5Repeats_FailedSamples, all = TRUE)
      } else {
      stop(paste("The current assaylist entry", assaylist[i], "does not match the expected naming convention"))
  }
}




```





# Assemble the pass/fail dataframes

```{r AssembleAllFrames}

# For EE_AllPasses
if(exists("EE_AllPasses") && !is.null(EE_AllPasses)){
  EE_PassDateList <- as.data.frame(EE_AllPasses$assayfile)
  colnames(EE_PassDateList) <- c("assayfile")
  EE_PassDateList <- EE_PassDateList %>%
    mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
    mutate(assayfile = str_remove(assayfile, folderMFI))
  EE_PassDateList$assayfile <- sub("_.*", "", EE_PassDateList$assayfile)
  
  # Add date column to the passes sheet
  EE_AllPasses <- add_column(EE_AllPasses, EE_PassDateList$assayfile, .after = 1)
  
  # Rename the date column
  colnames(EE_AllPasses)[2] <- "Assay_Passed_Date_EE"
  
  # Rearrange
  EE_AllPasses <- EE_AllPasses %>%
    dplyr::select(1, Assay_Passed_Date_EE, assayfile, everything())
  
  # Rename
  EE_AllPasses <- EE_AllPasses %>%
    rename(raw_file_path_EE = assayfile)
}

# For GP_AllPasses
if(exists("GP_AllPasses") && !is.null(GP_AllPasses)){
  GP_PassDateList <- as.data.frame(GP_AllPasses$assayfile)
  colnames(GP_PassDateList) <- c("assayfile")
  GP_PassDateList <- GP_PassDateList %>%
    mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
    mutate(assayfile = str_remove(assayfile, folderMFI))
  GP_PassDateList$assayfile <- sub("_.*", "", GP_PassDateList$assayfile)
  
  # Add date column to the passes sheet
  GP_AllPasses <- add_column(GP_AllPasses, GP_PassDateList$assayfile, .after = 1)
  
  # Rename the date column
  colnames(GP_AllPasses)[2] <- "Assay_Passed_Date_GP"
  
  # Rearrange
  GP_AllPasses <- GP_AllPasses %>%
    dplyr::select(1, Assay_Passed_Date_GP, assayfile, everything())
  
  # Rename
  GP_AllPasses <- GP_AllPasses %>%
    rename(raw_file_path_GP = assayfile)
}

# For ad5_AllPasses
if(exists("ad5_AllPasses") && !is.null(ad5_AllPasses)){
  ad5_PassDateList <- as.data.frame(ad5_AllPasses$assayfile)
  colnames(ad5_PassDateList) <- c("assayfile")
  ad5_PassDateList <- ad5_PassDateList %>%
    mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
    mutate(assayfile = str_remove(assayfile, folderMFI))
  ad5_PassDateList$assayfile <- sub("_.*", "", ad5_PassDateList$assayfile)
  
  # Add date column to the passes sheet
  ad5_AllPasses <- add_column(ad5_AllPasses, ad5_PassDateList$assayfile, .after = 1)
  
  # Rename the date column
  colnames(ad5_AllPasses)[2] <- "Assay_Passed_Date_ad5"
  
  # Rearrange
  ad5_AllPasses <- ad5_AllPasses %>%
    dplyr::select(1, Assay_Passed_Date_ad5, assayfile, everything())
  
  # Rename
  ad5_AllPasses <- ad5_AllPasses %>%
    rename(raw_file_path_ad5 = assayfile)
}

# For ad4and5_AllPasses
if(exists("ad4and5_AllPasses") && !is.null(ad4and5_AllPasses)){
  ad4and5_PassDateList <- as.data.frame(ad4and5_AllPasses$assayfile)
  colnames(ad4and5_PassDateList) <- c("assayfile")
  ad4and5_PassDateList <- ad4and5_PassDateList %>%
    mutate(assayfile = str_remove(assayfile, workingDirectory)) %>%
    mutate(assayfile = str_remove(assayfile, folderMFI))
  ad4and5_PassDateList$assayfile <- sub("_.*", "", ad4and5_PassDateList$assayfile)
  
  # Add date column to the passes sheet
  ad4and5_AllPasses <- add_column(ad4and5_AllPasses, ad4and5_PassDateList$assayfile, .after = 1)
  
  # Rename the date column
  colnames(ad4and5_AllPasses)[2] <- "Assay_Passed_Date_ad4and5"
  
  # Rearrange
  ad4and5_AllPasses <- ad4and5_AllPasses %>%
    dplyr::select(1, Assay_Passed_Date_ad4and5, assayfile, everything())
  
  # Rename
  ad4and5_AllPasses <- ad4and5_AllPasses %>%
    rename(raw_file_path_ad4and5 = assayfile)
}

# List of all data frames
FailQClist <- list(QCfirstEverythingElse, QCfirstGlycoprotein, QCrerunsEverythingElse, QCrerunsGlycoprotein, QCrepeatsEverythingElse, QCrepeatsGlycoprotein, QCfirstAD5, QCfirstAD4andAD5, QCrepeatsAD5, QCrepeatsAD4andAD5, QCrerunsAD5, QCrepeatsAD4andAD5)

# Remove NULL data frames from the list
FailQClist <- FailQClist[!sapply(FailQClist, is.null)]

# Check if the list is not empty
if(length(FailQClist) > 0) {
  # Find the maximum number of rows among the data frames
  max_rows <- max(sapply(FailQClist, nrow))
  
  # Ensure all data frames have the same number of rows
  FailQClist <- lapply(FailQClist, function(df) {
    # Create a new data frame with the correct number of rows and columns
    df_new <- as.data.frame(matrix(NA, nrow = max_rows, ncol = ncol(df)))
    colnames(df_new) <- colnames(df)
    
    # Replace the top part with the original data only if df has more than zero rows
    if (nrow(df) > 0) {
      df_new[1:nrow(df), ] <- df
    }
    
    return(df_new)
  })
  
  # Use cbind to combine all data frames
  MasterFailedQCFile <- do.call(cbind, FailQClist)
  
  # Replace NA values with blank spaces
  MasterFailedQCFile[is.na(MasterFailedQCFile)] <- ""
} else {
  print("No failing samples detected in data set")
}

# Write out the failed samples
MasterFailedQCFile[MasterFailedQCFile == "NA"] <- ""
write.csv(MasterFailedQCFile, paste0(workingDirectory, folderOutput, projectName, "_data-fails-qc.csv"), row.names = FALSE)

# Same process for passes
PassedQClist <- list(EE_AllPasses, GP_AllPasses, ad5_AllPasses, ad4and5_AllPasses)

# Remove NULL data frames from the list
PassedQClist <- PassedQClist[!sapply(PassedQClist, is.null)]

# Check if the list is not empty
if(length(PassedQClist) > 0) {
  # Initialize an empty data frame
  MasterSamplesPassedQCFile <- data.frame()

  # Loop through each data frame in the list
  for(df in PassedQClist) {
    # If the master data frame is empty, assign the first data frame to it
    if(nrow(MasterSamplesPassedQCFile) == 0) {
      MasterSamplesPassedQCFile <- df
    } else {
      # If the master data frame is not empty, merge it with the current data frame
      MasterSamplesPassedQCFile <- merge(MasterSamplesPassedQCFile, df, all = TRUE)
    }
  }

  # Replace NA values with blank spaces
  MasterSamplesPassedQCFile[is.na(MasterSamplesPassedQCFile)] <- ""

  # Write out the passed samples
  write.csv(MasterSamplesPassedQCFile, paste0(workingDirectory, folderOutput, projectName, "_data-pass-qc.csv"), row.names = FALSE)
}


# Create a list with the two data frames
QClist <- list(MasterSamplesPassedQCFile, MasterFailedQCFile)

# Remove NULL data frames from the list
QClist <- QClist[!sapply(QClist, is.null)]

# Check if the list is not empty
if(length(QClist) > 0) {
  # Find the maximum number of rows among the data frames
  max_rows <- max(sapply(QClist, nrow))
  
  # Ensure all data frames have the same number of rows
  QClist <- lapply(QClist, function(df) {
    # Create a new data frame with the correct number of rows and columns
    df_new <- as.data.frame(matrix(NA, nrow = max_rows, ncol = ncol(df)))
    colnames(df_new) <- colnames(df)
    
    # Replace the top part with the original data
    df_new[1:nrow(df), ] <- df
    
    return(df_new)
  })
}



```

# Assemble summary file and print

```{r}

# Use cbind to combine all data frames
SummaryFile <- do.call(cbind, QClist)

# Add new columns to the data frame
new_columns <- data.frame(primary_QC_script = rep("", nrow(SummaryFile)),
                          primary_QC_date = rep("", nrow(SummaryFile)),
                          secondary_QC_date = rep("", nrow(SummaryFile)),
                          secondary_QC_initial = rep("", nrow(SummaryFile)))

# Combine the new columns with the existing data frame
SummaryFile <- cbind(SummaryFile[1], new_columns, SummaryFile[-1])

# Find columns with "sampledescription" in their names
cols <- grep("sampledescription", colnames(SummaryFile))

# Get unique values from these columns
unique_values <- unique(unlist(SummaryFile[, cols]))

# Exclude blank spaces
unique_values <- unique_values[unique_values != ""]

# Identify the unique values that do not already exist in the first column
new_values <- setdiff(unique_values, SummaryFile[, 1])

# Create a new data frame with only new_values
new_SummaryFile <- data.frame(sampledescription = new_values)

# Full join SummaryFile to new_SummaryFile by sampledescription
SummaryFile <- plyr::join(SummaryFile, new_SummaryFile, by = "sampledescription", type = "full")

# Keep only the first column
SummaryFile <- SummaryFile[, 1, drop = FALSE]
SummaryFile <- na.omit(SummaryFile, "sampledescription")

# Filter out all blank values from SummaryFile
SummaryFile <- dplyr::filter(SummaryFile, !is.na(SummaryFile$sampledescription) & SummaryFile$sampledescription != "")

# Check if SummaryFile is a data frame
if (class(SummaryFile) != "data.frame") {
  # Convert SummaryFile to a data frame
  SummaryFile <- as.data.frame(SummaryFile)
}

# Order by sampledescription
SummaryFile <- SummaryFile[order(SummaryFile$sampledescription),, drop = FALSE]

if (!is.null(EE_AllPasses) && nrow(EE_AllPasses) > 0) {
  SummaryFile <- dplyr::left_join(SummaryFile, EE_AllPasses, by = "sampledescription")
}

if (!is.null(GP_AllPasses) && nrow(GP_AllPasses) > 0) {
  SummaryFile <- dplyr::left_join(SummaryFile, GP_AllPasses, by = "sampledescription")
}

if(exists("ad4_AllPasses") && !is.null(ad4_AllPasses) && nrow(ad4_AllPasses) > 0){
  SummaryFile <- dplyr::left_join(SummaryFile, ad4_AllPasses, by = "sampledescription")
}

if(exists("ad4and5_AllPasses") && !is.null(ad4and5_AllPasses) && nrow(ad4and5_AllPasses) > 0){
  SummaryFile <- dplyr::left_join(SummaryFile, ad4and5_AllPasses, by = "sampledescription")
}

if (!is.null(QCfirstEverythingElse) && nrow(QCfirstEverythingElse) > 0) {
  SummaryFile <- dplyr::left_join(SummaryFile, QCfirstEverythingElse, by = "sampledescription")
}

if (!is.null(QCfirstGlycoprotein) && nrow(QCfirstGlycoprotein) > 0) {
  SummaryFile <- dplyr::left_join(SummaryFile, QCfirstGlycoprotein, by = "sampledescription")
}

if (!is.null(QCrerunsEverythingElse) && nrow(QCrerunsEverythingElse) > 0) {
  SummaryFile <- dplyr::left_join(SummaryFile, QCrerunsEverythingElse, by = "sampledescription")
}

if (!is.null(QCrerunsGlycoprotein) && nrow(QCrerunsGlycoprotein) > 0) {
  SummaryFile <- dplyr::left_join(SummaryFile, QCrerunsGlycoprotein, by = "sampledescription")
}

if (!is.null(QCrepeatsEverythingElse) && nrow(QCrepeatsEverythingElse) > 0) {
  SummaryFile <- dplyr::left_join(SummaryFile, QCrepeatsEverythingElse, by = "sampledescription")
}

if (!is.null(QCrepeatsGlycoprotein) && nrow(QCrepeatsGlycoprotein) > 0) {
  SummaryFile <- dplyr::left_join(SummaryFile, QCrepeatsGlycoprotein, by = "sampledescription")
}

if(exists("QCfirstAD5") && !is.null(QCfirstAD5) && nrow(QCfirstAD5) > 0){
  SummaryFile <- dplyr::left_join(SummaryFile, QCfirstAD5, by = "sampledescription")
}

if(exists("QCfirstAD4andAD5") && !is.null(QCfirstAD4andAD5) && nrow(QCfirstAD4andAD5) > 0){
  SummaryFile <- dplyr::left_join(SummaryFile, QCfirstAD4andAD5, by = "sampledescription")
}

if(exists("QCrepeatsAD5") && !is.null(QCrepeatsAD5) && nrow(QCrepeatsAD5) > 0){
  SummaryFile <- dplyr::left_join(SummaryFile, QCrepeatsAD5, by = "sampledescription")
}

if(exists("QCrepeatsAD4andAD5") && !is.null(QCrepeatsAD4andAD5) && nrow(QCrepeatsAD4andAD5) > 0){
  SummaryFile <- dplyr::left_join(SummaryFile, QCrepeatsAD4andAD5, by = "sampledescription")
}

if(exists("QCrerunsAD5") && !is.null(QCrerunsAD5) && nrow(QCrerunsAD5) > 0){
  SummaryFile <- dplyr::left_join(SummaryFile, QCrerunsAD5, by = "sampledescription")
}

if(exists("QCrepeatsAD4andAD5") && !is.null(QCrepeatsAD4andAD5) && nrow(QCrepeatsAD4andAD5) > 0){
  SummaryFile <- dplyr::left_join(SummaryFile, QCrepeatsAD4andAD5, by = "sampledescription")
}

# Get column names
col_names <- colnames(SummaryFile)

# Remove .x and .y suffixes along with anything that follows
new_col_names <- sub("\\.x.*$", "", col_names)
new_col_names <- sub("\\.y.*$", "", new_col_names)

# Assign new column names to SummaryFile
colnames(SummaryFile) <- new_col_names

# Add new columns to the data frame
new_columns <- data.frame(primary_QC_script = rep("", nrow(SummaryFile)),
                          primary_QC_date = rep("", nrow(SummaryFile)),
                          secondary_QC_date = rep("", nrow(SummaryFile)),
                          secondary_QC_initial = rep("", nrow(SummaryFile)))

# Combine the new columns with the existing data frame
SummaryFile <- cbind(SummaryFile[1], new_columns, SummaryFile[-1])

# Replace NA values with blank spaces
SummaryFile[is.na(SummaryFile)] <- ""

# Remove duplicate rows in sampledescription
SummaryFile <- dplyr::distinct(SummaryFile, sampledescription, .keep_all = TRUE)

# Read the CSV file
data <- read.csv(paste0(workingDirectory, folderMFI, assaylist[1], "_MFIs-unfiltered.csv"))

# Get the file info
info <- file.info(paste0(workingDirectory, folderMFI, assaylist[1], "_MFIs-unfiltered.csv"))

# Extract the modification time
mod_time <- info$mtime

# Convert the modification time to Date only (without time)
mod_date <- as.Date(mod_time)

# Add the script version and date to the data frame
SummaryFile$primary_QC_script <- primaryQCscriptName
SummaryFile$primary_QC_date <- mod_date

# Write out the summary file
write.csv(SummaryFile, paste0(workingDirectory, folderOutput, projectName, "_summary-file.csv"), row.names = FALSE)

```

